--Oracle Bitmap Index

--We will use the members_new table created in the CREATE INDEX tutorial for the demonstration.
---The following query  finds all female members from the  members_new table:
SELECT 
    *
FROM
    members_new
WHERE
    gender = 'F';
    
--To create a bitmap index for the gender column, use the following statement:
CREATE BITMAP INDEX members_gender_i
ON members_new(gender);

EXPLAIN PLAN FOR 
SELECT 
    *
FROM
    members_new
WHERE
    gender = 'F';

    
SELECT 
    PLAN_TABLE_OUTPUT 
FROM 
    TABLE(DBMS_XPLAN.DISPLAY());
    
--The following statement creates a new table named bitmap_index_demo:
CREATE TABLE bitmap_index_demo(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    active NUMBER NOT NULL,
    PRIMARY KEY(id)
);
--And the following statement creates a bitmap index on the active column:
CREATE BITMAP INDEX bitmap_index_demo_active_i
ON bitmap_index_demo(active);
--Open two sessions and repeatedly execute one of the following statements in each session:
INSERT INTO bitmap_index_demo(active) 
VALUES(1);

INSERT INTO bitmap_index_demo(active) 
VALUES(0);
